#! /bin/sh
set -e

if [ "$1" = "upgrade" ]; then
	# save portmap state; will be reread when portmap start is run
	pmap_dump >/var/run/portmap.upgrade-state
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/portmap" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d portmap stop || exit $?
	else
		/etc/init.d/portmap stop || exit $?
	fi
fi
# End automatically added section

